# Generated by Django 3.0.5 on 2020-05-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_auto_20200522_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre completo'),
        ),
    ]
